### PR TITLE
little fix of #54 issue

### LINKED ISSUE #54: Unexpected keyword argument 'probability' on regression models
[HyperoptEstimator fit method](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/estimator.py#L656) crashes with ''TypeError: __init__() got an unexpected keyword argument 'probability'" on a **regression** models.

### PR DESCRIPTION
**Pull request by MrFroll**
I'd like to fix #54 issue by this pull request.

### CODE REVIEW

**Comment by bjkomer** [comment]
Thanks for the PR! This will work, but I think it makes a little more sense to only add the probability parameter to SVC, rather than adding it to both before removing it from SVR.

There is a function that takes care of SVC specific parameters around line [437](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/components.py#L437) where it can be added. It will then no longer be needed in the `_svm_hp_space` function (line 387 and 432). The probability parameter isn't one that is optimized, so its default can be `False`.

**Comment by MrFroll** [comment]
Thank you for advice. I think you solution is more correct.

**Comment by bjkomer** [comment]
This is very close, there now just needs to be a way for the user to set the probability parameter if they choose. It needs to show up as an argument in the `svc_kernel` and `_svc_hp_space` functions. The latter function will look something like this:

```
def _svc_hp_space(name_func, random_state=None, probability=False):
     hp_space = dict(
         random_state = _random_state(name_func('rstate'),random_state),
         probability=probability
     )
```

**Comment by MrFroll** [comment]
Ok, I see. @bjkomer, what do you think about user API? Should this parameter be as a part of [svc](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/components.py#L496)  `**kwarks` argument or new parameter `probability` of [svc](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/components.py#L496) function?

**Comment by bjkomer** [comment]
I think it should just be part of `**kwargs` for the [`svc`](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/components.py#L496) function, but appear in the argument list for [`svc_kernel`](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/components.py#L457). Very similar to how the `random_state` parameter is used.

**Comment by MrFroll** [comment]
Done

**Pull request merged**
